version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: secret
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER:  ${DATABASE_USER}
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

